version: '3'

services:
  backend:
    build: ./backend
    ports:
      - 4000:3001
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      # - ./backend/good_corner_typeorm.sqlite:/app/good_corner_typeorm.sqlite
      - ./backend/.env:/app/.env:rw
      - ./backend/src:/app/src:rw
      - ./backend/node_modules:/app/node_modules
      - ./backend/package.json:/app/package.json:rw
      - ./backend/migrations:/app/migrations:rw
    healthcheck:
      test: 'curl --fail --request POST --header ''content-type: application/json'' --url ''http://localhost:4000'' --data ''{"query":"query { __typename }"}'' || exit 1'
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      db:
        condition: service_healthy


  frontend:
    build: ./frontend
    command: npm run dev
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_HOST=127.0.0.1 
    volumes:
      - ./frontend/src:/app/src:rw
      - ./frontend/package.json:/app/package.json:rw
    healthcheck:
      test: "curl --fail --request GET --url 'http://localhost:3000' || exit 1"
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: goodcorner
      POSTGRES_PASSWORD: password
      POSTGRES_DB: goodcornerdb
      PGDATA: customDataFolder
    volumes:
      - ./dbData:/var/lib/postgresql/data/customDataFolder
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d goodcornerdb -U goodcorner" ]
      interval: 5s
      timeout: 5s
      retries: 10

  images:
    build: ./images
    volumes:
      - ./images/src:/app/src
      - ./images/uploads:/app/uploads
    ports:
      - 8000:8000

  e2e:
    build: ./e2e
    volumes:
      - ./e2e/playwright-report:/app/playwright-report
      - ./e2e/test-results:/app/test-results
    depends_on:
      frontend:
        condition: service_healthy